//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowAndReturn
    {
        public int bandr_id { get; set; }
        public string bandr_borrowno { get; set; }
        public string bandr_name { get; set; }
        public System.DateTime bandr_borrowtime { get; set; }
        public int bandr_depart { get; set; }
        public string bandr_reason { get; set; }
        public Nullable<System.DateTime> bandr_returntime { get; set; }
        public int bandr_wareid { get; set; }
        public string bandr_remark { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Warehous Warehous { get; set; }
    }
}
