//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetManage_DBEntities : DbContext
    {
        public AssetManage_DBEntities()
            : base("name=AssetManage_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminPersonalInfo> AdminPersonalInfo { get; set; }
        public DbSet<AssetsClass> AssetsClass { get; set; }
        public DbSet<BorrowAndReturn> BorrowAndReturn { get; set; }
        public DbSet<Brand> Brand { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Scrap> Scrap { get; set; }
        public DbSet<ScrapType> ScrapType { get; set; }
        public DbSet<StoragePlace> StoragePlace { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserPrivileg> UserPrivileg { get; set; }
        public DbSet<Warehous> Warehous { get; set; }
    }
}
