//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoragePlace
    {
        public StoragePlace()
        {
            this.Warehous = new HashSet<Warehous>();
        }
    
        public int place_id { get; set; }
        public string place_name { get; set; }
        public string place_type { get; set; }
        public int place_state { get; set; }
        public string place_remark { get; set; }
    
        public virtual ICollection<Warehous> Warehous { get; set; }
    }
}
