//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Warehous = new HashSet<Warehous>();
        }
    
        public int sup_id { get; set; }
        public string sup_name { get; set; }
        public string sup_type { get; set; }
        public int sup_state { get; set; }
        public string sup_iphone { get; set; }
        public string sup_contact { get; set; }
        public string sup_address { get; set; }
    
        public virtual ICollection<Warehous> Warehous { get; set; }
    }
}
