//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehous
    {
        public Warehous()
        {
            this.BorrowAndReturn = new HashSet<BorrowAndReturn>();
            this.Scrap = new HashSet<Scrap>();
        }
    
        public int ware_id { get; set; }
        public string ware_no { get; set; }
        public string ware_name { get; set; }
        public int ware_class { get; set; }
        public int ware_sup { get; set; }
        public int ware_brand { get; set; }
        public Nullable<System.DateTime> ware_addtime { get; set; }
        public int ware_place { get; set; }
        public int ware_brstate { get; set; }
        public int ware_scrstate { get; set; }
    
        public virtual AssetsClass AssetsClass { get; set; }
        public virtual ICollection<BorrowAndReturn> BorrowAndReturn { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Scrap> Scrap { get; set; }
        public virtual StoragePlace StoragePlace { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
